// Copyright 2025 International Digital Economy Academy
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

///|
pub type BroadPhase = @collision.BroadPhase3D

///|
pub type Collider = @collision.Collider3D

///|
pub type ColliderBuilder = @collision.ColliderBuilder3D

///|
pub type ColliderHandle = @collision.ColliderHandle3D

///|
pub type ColliderSet = @collision.ColliderSet3D

///|
pub type EventHandler = @pipeline.EventHandler3D

///|
pub type EffectiveCharacterMovement = @control.EffectiveMovement3DReal

///|
pub type GenericJoint = @dynamics.GenericJoint

///|
pub type GenericJointBuilder = @dynamics.GenericJoint3DRealBuilder

///|
pub type DynamicRayCastVehicleController = @control.DynamicRayCastVehicleController3DReal

///|
pub type IntegrationParameters = @dynamics.IntegrationParameters

///|
pub type IslandManager = @dynamics.IslandManager3D

///|
pub type ImpulseJointSet = @dynamics.JointSet3DReal

///|
pub type Multibody = @dynamics.Multibody3DReal

///|
pub type MultibodyJointSet = @dynamics.MultibodyJointSet3DReal

///|
pub type NarrowPhase = @collision.NarrowPhase3D

///|
pub type PhysicsHooks = @pipeline.PhysicsHooks3D

///|
pub type PhysicsPipeline = @pipeline.PhysicsPipeline3DReal

///|
pub type QueryPipeline = @collision.QueryPipeline3DReal

///|
pub type RevoluteJoint = @dynamics.RevoluteJoint

///|
pub type RevoluteJointBuilder = @dynamics.RevoluteJointBuilder3

///|
pub type RigidBody = @dynamics.RigidBody3D

///|
pub type RigidBodyBuilder = @dynamics.RigidBodyBuilder3D

///|
pub type RigidBodyHandle = @dynamics.RigidBodyHandle

///|
pub type RigidBodySet = @dynamics.RigidBodySet3D

///|
pub type RopeJointSet = @dynamics.RopeJointSet3DReal

///|
pub type Shape = @collision.Shape3D

///|
pub type Vec3 = @core.Vec3
